// @flow
type LinksType = {
  LOAD_MY: "LINKS_LOAD_MY",
  LOAD_ALL: "LINKS_LOAD_ALL",
  REQUESTED: "LINKS_REQUESTED",
  REQUESTED_SUCCEEDED: "LINKS_REQUESTED_SUCCEEDED",
  REQUESTED_FAILED: "LINKS_REQUESTED_FAILED"
};

export const LINKS: LinksType = {
  LOAD_MY: "LINKS_LOAD_MY",
  LOAD_ALL: "LINKS_LOAD_ALL",
  REQUESTED: "LINKS_REQUESTED",
  REQUESTED_SUCCEEDED: "LINKS_REQUESTED_SUCCEEDED",
  REQUESTED_FAILED: "LINKS_REQUESTED_FAILED"
};

export const CLEAR_USER: "CLEAR_USER" = "CLEAR_USER";
export const SAVE_USER: "SAVE_USER" = "SAVE_USER";

export const LOGIN: "LOGIN" = "LOGIN";
export const LOGOUT: "LOGOUT" = "LOGOUT";

export const AUTH_DISABLE: "AUTH_DISABLE" = "AUTH_DISABLE";
export const AUTH_REQUESTED: "AUTH_REQUESTED" = "AUTH_REQUESTED";
export const AUTH_SUCCEEDED: "AUTH_SUCCEEDED" = "AUTH_SUCCEEDED";
export const AUTH_FAILED: "AUTH_FAILED" = "AUTH_FAILED";

export const FETCH_LINK: "FETCH_LINK" = "FETCH_LINK";
export const FETCH_PROFILE: "FETCH_PROFILE" = "FETCH_PROFILE";
