// @flow
export const LINKS_LOAD_MY: "LINKS_LOAD_MY" = "LINKS_LOAD_MY";
export const LINKS_LOAD_ALL: "LINKS_LOAD_ALL" = "LINKS_LOAD_ALL";
export const LINKS_LOAD_REQUESTED: "LINKS_LOAD_REQUESTED" =
  "LINKS_LOAD_REQUESTED";
export const LINKS_LOAD_SUCCEEDED: "LINKS_LOAD_SUCCEEDED" =
  "LINKS_LOAD_SUCCEEDED";
export const LINKS_LOAD_FAILED: "LINKS_LOAD_FAILED" = "LINKS_LOAD_FAILED";

export const CREATE_LINK: "CREATE_LINK" = "CREATE_LINK";
export const CREATE_LINK_REQUESTED: "CREATE_LINK_REQUESTED" =
  "CREATE_LINK_REQUESTED";
export const CREATE_LINK_SUCCEEDED: "CREATE_LINK_SUCCEEDED" =
  "CREATE_LINK_SUCCEEDED";
export const CREATE_LINK_FAILED: "CREATE_LINK_FAILED" = "CREATE_LINK_FAILED";

export const FETCH_LINK: "FETCH_LINK" = "FETCH_LINK";
export const FETCH_PROFILE: "FETCH_PROFILE" = "FETCH_PROFILE";
